springdoc:
  swagger-ui:
    default-model-expand-depth: 3
  api-docs:
    path: /openapi.json
    resolve-schema-properties: true
  extension:
    version: 1.0.0
    title: "Opendata Bridge Transform API"
    description: "Opendata Bridge Transform API"
